export const routeLinks = {
    login: '/auth/login',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    waitingPassword: '/auth/waiting-password',
    associeHome: '/',
    associe: '/associe',
    associeDossiersStandards: '/associe/dossiers/standards',
    associeDossiersStructures: '/associe/dossiers/structures',
    associePetiteCaisse: '/associe/petite-caisse',
    associeClientsStructures: '/associe/clients-structures',
    associeDemandeConge: '/associe/demande-conge',
    associeEcritures: '/associe/ecritures',
    associeCondense: '/associe/condense',
    associeRapport: '/associe/rapport',
    personnel: '/associe/personnel',
    secretaire: '/secretaire',
    dossiersStandards: '/secretaire/dossiers/standards',
    dossiersStructures: '/secretaire/dossiers/structures',
    petiteCaisse: '/secretaire/petite-caisse',
    clientsStructures: '/secretaire/clients-structures',
    demandeConge: '/secretaire/demande-conge',
    ecritures: '/secretaire/ecritures',
    secretaireCondense: '/secretaire/condense',
    secretaireRapport: '/secretaire/rapport',
    collaborateur: '/collaborateur',
    collaborateurCondense: '/collaborateur/condense',
    collaborateurRapport: '/collaborateur/rapport',
    collaborateurDemandeConge: '/collaborateur/demande-conge',
    standards: '/collaborateur/dossiers/standards',
    structures: '/collaborateur/dossiers/structurees',
}

export const apiLinks = {
    login: '/auth/api/login',
    register: '/auth/api/register',
    logout: '/auth/api/logout',
    forgotPassword: '/auth/api/forgetpassword',
    resetPassword: `/auth/api/resetPassword`,
    associeHome: '/',
    associePersonnel: '/associe/api/personnel',
    secretaire: '/secretaire',
    dossiersStructures: '/api/dossier/structure',
    dossiersStandards: '/api/dossier/standard',
    clientsStructures: '/secretaire/api/clients-structures',
    petiteCaisse: '/secretaire/api/petite-caisse',
    collaborateur: '/collaborateur',
    rapport: '/collaborateur/api/rapport/rapport_daily',
    condanse: '/collaborateur/condanse',
    apistandardscollab: '/collaborateur/api//dossiers/standard',
    apistrucurescollab: '/collaborateur/api/dossiers/structure',
    demandeconge: '/collaborateur/api/demande-conge',
    listedossierscollab: '/collaborateur/api/dossiers/',
    visualiserapport: "/associe/api/visualiserapport",
    conge: "/associe/api/conges",
    ajouteconge: "/associe/api/ajouteconge",
    rapportAssocie: "/associe/api/rapport",
    ecrituresAssocie: "/associe/api/ecriture/liste",
    rapportaudiance:"/collaborateur/api/rapport-audiance"
}